#!/bin/bash

while :
do
   if i2cget -f -y 1 0x48 64 | grep 0x38 >/dev/nul 2>&1
   then
      echo 0 >/sys/class/gpio/gpio65/value
      sleep 1
      echo 1 >/sys/class/gpio/gpio65/value
      sleep 1
   fi
done
