#!/bin/bash

echo none > /sys/class/leds/rockpis:blue:user/trigger

while :
do
   if  cat /proc/asound/card0/pcm0p/sub0/hw_params |grep closed >/dev/nul 2>&1 || i2cget -f -y 1 0x48 64 | grep 0x30 >/dev/nul 2>&1
   then
       echo default-on > /sys/class/leds/rockpis:green:power/trigger
       if amixer cget numid=3 | grep "values=1" >/dev/nul 2>&1
       then
          amixer cset numid=3 0 >/dev/nul 2>&1
       fi
   fi
   if  cat /proc/asound/card0/pcm0p/sub0/hw_params |grep rate >/dev/nul 2>&1
   then
       echo none > /sys/class/leds/rockpis:green:power/trigger
       if amixer cget numid=3 | grep "values=0" >/dev/nul 2>&1
       then
          amixer cset numid=3 1 >/dev/nul 2>&1
       fi
   fi
done
